### ISSUE TITLE
Groupon module false positives

### ISSUE THREAD

**Issue by 0x27** [lightos/credmap#15]
While testing, I noticed that *all* credentials provided would provide a "positive" result for Groupon. Upon attempting to log in with the specified credentials, however, I was informed that the credentials were invalid.

Will attempt debugging of this at a later date.

**Comment by lightos** [comment]
Fixed in https://github.com/lightos/credmap/pull/16/commits/72ef53795dea1fe304c25dc22285e08d1fc934e4
