### ISSUE TITLE
This is not a issue but a question about xml

### ISSUE THREAD

**Issue by Zawadidone** [lightos/credmap#22]
I wanna write a script that gets the xml properties of a url and then saves it in the websites folder do you have suggestions or methods to do that?

**Comment by lightos** [comment]
I just pushed the beginnings of v2 (https://github.com/lightos/credmap/tree/v2), which I started a year ago, but then got really busy with other things. In this version it is easier to create a generalized module which can handle many websites even if they are not in the websites folder.

For example, if you look at the code for the digitalocean module (https://github.com/lightos/credmap/blob/v2/websites/digitalocean.py#L23-L47), it is fairly general and that code could be expanded slightly to work on plenty of other websites, even if they are not in the websites folder.

I will try to finish v2 little by little, whenever I get the time to work on it.

**Comment by Zawadidone** [comment]
Okay thanks for the reaction let me know when your done.
