### ISSUE TITLE
Getting Proxy To work

### ISSUE THREAD

**Issue by n00py** [lightos/credmap#6]
Hello, I'm trying to add some modules but it's hard to debug without intercepting https, I tried to specify a proxy but it doesn't seem to work:

python credmap.py --email XXXXXX --password XXXXXXX --only XXXXX --proxy https://127.0.0.1:8080
![screen shot 2016-07-10 at 6 26 24 pm](https://cloud.githubusercontent.com/assets/14309124/16717519/d5b69534-46cb-11e6-812b-71b62d34dcdf.png)

I have Burp listening on local host, Burp is fine because it is proxying my web browser without issue.

**Comment by lightos** [comment]
I believe you have to install burp's certificate on the OS in order for python to work with burp's SSL cert. An example of how to do this on Windows can be found here: https://parsiya.net/blog/2016-02-21-installing-burp-certificate-authority-in-windows-certificate-store/

It should work after doing that:
![image](https://cloud.githubusercontent.com/assets/464835/16717685/08e4f7f0-46ce-11e6-82b8-1d7c98543575.png)

**Comment by n00py** [comment]
Got it to work on OSX as well.  Download Burp certificate, add to keychain, trust cert.
